"""
Train a custom model for one organization.

This wraps ``ml.training.train`` rather than reimplementing any of it. A custom
model is produced by exactly the same pipeline, with the same split discipline
and the same threshold selection, as the built-in one. That is the whole point:
if the two were trained differently, their numbers could not be compared, and
the model comparison screen would be meaningless.

What this module adds is the part that is specific to serving many
organizations:

* the uploaded CSV is converted to the pipeline's format and written inside the
  model's own directory, so a model always sits next to the exact data it was
  fitted on;
* the held-out evaluation is run immediately afterwards and stored with the
  model, so no model can ever be activated without measured results;
* every path is derived from ids the server generated, never from anything the
  user supplied.

A custom model is never activated automatically. Training produces a candidate;
a person has to approve it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from api.config.settings import settings
from api.database import SessionLocal
from api.models import DatasetRecord, ModelRecord
from api.services import datasets as ds_util

#: The columns the pipeline reads from a raw CSV.
RAW_COLUMNS = ["Time", "Source", "Target", "Amount", "Location", "Type", "Labels"]


def model_dir(model_id: str) -> Path:
    """
    Where one model's files live.

    The id is generated by the server and contains only hex and an underscore,
    so it cannot escape the directory. It is still resolved and checked below,
    because a path built from an identifier is exactly the kind of thing that
    quietly becomes user controlled later.
    """
    root = Path(settings.user_model_dir).resolve()
    path = (root / model_id).resolve()
    if not str(path).startswith(str(root)):
        raise ValueError("refusing a model path outside the model directory")
    return path


def _write_training_csv(dataset: DatasetRecord, destination: Path) -> tuple[int, int]:
    """
    Convert the uploaded file into the pipeline's raw format.

    Returns the row count and the number of labeled rows, both measured from
    the converted frame rather than trusted from the upload record.
    """
    source = ds_util.upload_path(dataset.stored_name)
    # The default cap is the test-dataset limit, which would quietly truncate a
    # training file and train on part of it without saying so.
    frame = ds_util.read_csv(source, max_rows=settings.max_training_rows)
    mapping = dataset.validation.get("mapping") or ds_util.detect_mapping(frame)
    spark_frame = ds_util.to_spark_frame(frame, mapping)

    out = spark_frame[RAW_COLUMNS]
    out.to_csv(destination, index=False)

    n_rows = int(len(out))
    n_labeled = int((out["Labels"] != 2).sum())
    return n_rows, n_labeled


def train_custom_model(
    model_id: str,
    dataset_id: str,
    report: Callable[[str, float], None],
) -> dict:
    """
    The unit of work the job runner executes.

    ``report`` is the job runner's progress callback. The stages it receives
    are the pipeline's real stages, so the progress bar moves when work
    finishes rather than on a timer.
    """
    from ml.config import CONFIG
    from ml.evaluation.evaluate import evaluate
    from ml.training.train import train

    directory = model_dir(model_id)
    directory.mkdir(parents=True, exist_ok=True)
    raw_csv = directory / "training_data.csv"
    report_dir = directory / "reports"
    report_dir.mkdir(exist_ok=True)

    with SessionLocal() as db:
        dataset = db.get(DatasetRecord, dataset_id)
        if dataset is None:
            raise RuntimeError("The dataset was removed before training started.")
        report("preparing your data", 0.02)
        n_rows, n_labeled = _write_training_csv(dataset, raw_csv)

    if n_labeled < settings.min_training_rows:
        raise RuntimeError(
            f"Only {n_labeled:,} rows carry a usable label, and training needs "
            f"at least {settings.min_training_rows:,}."
        )

    # Training and evaluation both read the same CSV, so the split boundaries
    # match and the test rows really are rows the model never saw.
    bundle = train(
        cfg=CONFIG,
        artifact_dir=directory,
        verbose=False,
        raw_path=raw_csv,
        progress=lambda stage, fraction: report(stage, 0.05 + fraction * 0.75),
    )

    report("held-out evaluation", 0.85)
    evaluation = evaluate(
        cfg=CONFIG,
        artifact_dir=directory,
        report_dir=report_dir,
        verbose=False,
        raw_path=raw_csv,
    )

    report("saving", 0.97)
    metrics = _summarise(evaluation, bundle.metadata, n_rows, n_labeled)

    with SessionLocal() as db:
        model = db.get(ModelRecord, model_id)
        if model is not None:
            model.status = "trained"
            model.version = bundle.metadata.get("model_version", "custom-v1")
            model.metrics = metrics
            model.artifact_path = str(directory)
            db.commit()

    return metrics


def _summarise(evaluation: dict, metadata: dict, n_rows: int, n_labeled: int) -> dict:
    """
    Pull out the numbers a person needs to decide whether to approve this.

    Only held-out test numbers are promoted to the top level. Training and
    validation numbers stay inside ``splits``, because quoting them as results
    is how a model gets approved on the strength of what it memorised.
    """
    by_split = {r["split"]: r for r in evaluation.get("ranking_by_split", [])}
    test = by_split.get("test", {})
    operating = {
        r["mode"]: r for r in evaluation.get("operating_points_test", [])
    }
    balanced = operating.get("balanced", {})

    return {
        "measured_on": "held-out test",
        "n_rows": n_rows,
        "n_labeled": n_labeled,
        "test": {
            "n": test.get("n"),
            "n_positive": test.get("n_positive"),
            "base_rate": test.get("base_rate"),
            "pr_auc": test.get("pr_auc"),
            "roc_auc": test.get("roc_auc"),
            "brier": test.get("brier"),
        },
        "balanced": {
            "precision": balanced.get("precision"),
            "recall": balanced.get("recall"),
            "f1": balanced.get("f1"),
            "fpr": balanced.get("fpr"),
            "fnr": balanced.get("fnr"),
            "review_threshold": balanced.get("review_threshold"),
            "block_threshold": balanced.get("block_threshold"),
            "tp": balanced.get("tp"),
            "fp": balanced.get("fp"),
            "tn": balanced.get("tn"),
            "fn": balanced.get("fn"),
        },
        "splits": evaluation.get("ranking_by_split", []),
        "operating_points": evaluation.get("operating_points_test", []),
        "drift": evaluation.get("drift"),
        "limitations": evaluation.get("limitations", []),
        "trained_at": metadata.get("created_utc"),
        "model_version": metadata.get("model_version"),
        "total_train_seconds": metadata.get("total_train_seconds"),
    }
