"""
Write the production ``.env`` onto the Spark server.

The file is piped over SSH rather than passed as an argument, so no secret ever
appears in a process list, a shell history or this script's output.

SESSION_SECRET is generated once and then preserved. It keys the HMAC that
hashes API keys, so replacing it would invalidate every key an organization has
already issued.

Database: the connection string comes from SUPABASE_DB_URL in the local
``.env``, which ``ops/supabase/role.py`` writes. That role reaches the ``spark``
schema and nothing else, so the project's shared postgres password is never
read, reset or used. Without that variable the server runs on SQLite.

Usage:
    python -m ops.server.env --host 13.232.127.102 --key path/to/key.pem
"""

from __future__ import annotations

import argparse
import re
import secrets
import subprocess

from ops.paths import ROOT

DOMAIN = "spark.spacesdrive.cc"

def local_env(key: str) -> str:
    f = ROOT / ".env"
    if not f.exists():
        return ""
    m = re.search(rf"^{re.escape(key)}=(.*)$", f.read_text(), re.MULTILINE)
    return m.group(1).strip() if m else ""

def ssh(host: str, key: str, command: str, stdin: str | None = None) -> str:
    p = subprocess.run(
        ["ssh", "-i", key, "-o", "StrictHostKeyChecking=accept-new",
         "-o", "ConnectTimeout=30", f"ubuntu@{host}", command],
        input=stdin, capture_output=True, text=True,
    )
    if p.returncode != 0:
        raise RuntimeError(p.stderr.strip()[:400])
    return p.stdout

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", required=True)
    ap.add_argument("--key", required=True)
    args = ap.parse_args()

    # Keep the secret the server already chose, if it has one.
    existing = ssh(args.host, args.key,
                   "grep '^SESSION_SECRET=' /opt/spark/.env 2>/dev/null | cut -d= -f2- || true").strip()
    session_secret = existing or secrets.token_urlsafe(48)
    print(f"session secret   {'preserved' if existing else 'generated'}")

    # Written by ops/supabase/role.py. It names a dedicated role whose rights
    # stop at the spark schema, so it is not the project's shared credential.
    database_url = local_env("SUPABASE_DB_URL")
    if database_url:
        print("database         Supabase PostgreSQL, spark schema, spark_app role")
    else:
        database_url = "sqlite:////opt/spark/data/spark.db"
        print("database         SQLite (run ops/supabase/role.py --apply to use Supabase)")

    env = f"""# Spark production. Generated by ops/server/env.py. Do not commit.
ENVIRONMENT=production
DEBUG=false
DATABASE_URL={database_url}
ARTIFACT_DIR=/opt/spark/artifacts
UPLOAD_DIR=/opt/spark/data/uploads
USER_MODEL_DIR=/opt/spark/data/user_models
FRONTEND_URL=https://{DOMAIN}
BACKEND_URL=https://{DOMAIN}
PUBLIC_DOMAIN={DOMAIN}
DOCS_DOMAIN=docs-{DOMAIN}
CORS_ORIGINS=https://{DOMAIN}
SUPABASE_URL={local_env('SUPABASE_URL')}
SUPABASE_ANON_KEY={local_env('SUPABASE_ANON_KEY')}
SESSION_SECRET={session_secret}
COOKIE_SECURE=true
COOKIE_SAMESITE=lax
EAGER_MODEL_LOAD=true
UPSTASH_REDIS_REST_URL={local_env('UPSTASH_REDIS_REST_URL')}
UPSTASH_REDIS_REST_TOKEN={local_env('UPSTASH_REDIS_REST_TOKEN')}
CACHE_TTL_SECONDS={local_env('CACHE_TTL_SECONDS') or '900'}
"""
    ssh(args.host, args.key,
        "cat > /opt/spark/.env && chmod 640 /opt/spark/.env && "
        "sudo chown ubuntu:spark /opt/spark/.env", stdin=env)
    names = ssh(args.host, args.key, "cut -d= -f1 /opt/spark/.env | grep -v '^#' | tr '\n' ' '")
    print(f"written          {names.strip()}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
